name: Publish Rust Crate

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Install cargo-release (optional for version bump automation)
      run: cargo install cargo-release

    - name: Verify the crate
      run: cargo check --release

    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_API_KEY }}
      run: cargo publish --allow-dirty